SELECT * FROM customer LIMIT 20;

--Q1 What is the total revenue generated by male vs female customers?
SELECT gender,SUM(purchase_amount) as revenue 
FROM customer
GROUP BY gender

--Q2 Which customers used a discount but still spent more than the purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3 Which are the top 5 products with the highest abg review rating?
select item_purchased,ROUND(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4Do subscribed customers spend more? compare avg spend total revenue b/w subscribers and non-subscribers.
select discount_applied as subscription_status,
COUNT(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by discount_applied
order by total_revenue,avg_spend desc;

--Q5 Which 5 products have the highest percentage with discounts applied?
select item_purchased,
ROUND(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q6  Segment customers into New,Returning,and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q7 What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() OVER(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q8 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select discount_applied as subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by discount_applied



